### ISSUE TITLE
Export .csv file from the nafdac db and create a database for the project

### ISSUE THREAD

**Issue by olawanlejoel** [InventorsDev/sdg-007#2]
Please visit the nafdac db and export the file then import it to our database so we can make use of it in this project.

**Comment by popoolatopzy** [comment]
@oyedeletemitope and I was able to export  all the nafdac database for drugs and upload it to our database,
We now have details of all register drugs approved by nafdac. 
[Uploading dvapp.sql…]()

**Comment by olawanlejoel** [comment]
Okay thanks Chiefs, weldone!

**Comment by olawanlejoel** [comment]
I have closed the issue since the task has been completed.
